### ISSUE TITLE
Sobre el proyecto servidor

### ISSUE THREAD

**Issue by delucas** [PuumPuumPuum/jrpg#2]
El proyecto `servidor` tiene como intención albergar la parte servidor del juego, no del chat.
Por favor, remuevan eso y/o transfórmenlo en el proyecto servidor de propósito general.

En cualquiera de los dos casos, las clases de `cliente` deberían haber terminado en tal proyecto, y no en `servidor`.

**Comment by martinferrarese** [comment]
Se eliminaron las clases incorrectas que correspondían a un chat y no al juego en sí.
